/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
puppeteer.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'stockx_com_product_category_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_SERVER = 'residential-proxy.scrapeops.io';
const PROXY_PORT = '8181';
const PROXY_USERNAME = 'scrapeops';
const PROXY_PASSWORD = API_KEY;

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            const domain = "https://stockx.com";
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            const text = (priceText || "").toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        let nextData = null;
        const nextDataScript = $("script#__NEXT_DATA__").first().html();
        if (nextDataScript) {
            try {
                nextData = JSON.parse(nextDataScript);
            } catch (e) {
                console.error("Error parsing __NEXT_DATA__");
            }
        }

        const outputData = {
            url: url,
            timestamp: new Date().toISOString(),
            appliedFilters: [],
            bannerImage: $("meta[property='og:image']").attr("content") || "",
        };

        const breadcrumbs = [];
        const breadcrumbSchema = $("script[data-testid='breadcrumb-schema']");
        if (breadcrumbSchema.length > 0) {
            breadcrumbSchema.each((i, el) => {
                try {
                    const ld = JSON.parse($(el).html());
                    if (ld.itemListElement) {
                        ld.itemListElement.forEach(item => {
                            if (item.item && item.item.name) {
                                breadcrumbs.push({
                                    name: item.item.name,
                                    url: makeAbsoluteURL(item.item['@id'])
                                });
                            }
                        });
                    }
                } catch (e) {}
            });
        }

        if (breadcrumbs.length === 0) {
            $("nav[data-testid='Breadcrumbs'] li").each((i, el) => {
                const $el = $(el);
                const name = ($el.find("a, span").last().text() || "").trim();
                const href = $el.find("a").attr("href");
                if (name && name !== "/") {
                    breadcrumbs.push({
                        name: name,
                        url: makeAbsoluteURL(href)
                    });
                }
            });
        }
        outputData.breadcrumbs = breadcrumbs;

        let catID = "";
        if (nextData && nextData.query) {
            catID = nextData.query.level1Category || "";
        }
        if (!catID) {
            const idAttr = $("h1[id^='categoryId-']").attr("id");
            if (idAttr) catID = idAttr.replace("categoryId-", "");
        }
        outputData.categoryId = catID;

        outputData.categoryName = $("h1").first().text().trim();
        const canonical = $("link[rel='canonical']").attr("href");
        outputData.categoryUrl = makeAbsoluteURL(canonical);

        const descriptionParts = [];
        $(".chakra-text").each((i, el) => {
            const classAttr = $(el).attr("class") || "";
            if (classAttr.includes("1o63kog")) {
                descriptionParts.push($(el).text().trim());
            }
        });
        outputData.description = descriptionParts.join("\n\n");

        const pagination = {
            currentPage: 1,
            nextPageUrl: null,
            prevPageUrl: null,
            resultsPerPage: 40,
            totalPages: 1,
            totalResults: 0,
        };

        if (nextData) {
            try {
                const queries = nextData.props?.pageProps?.states?.query?.value?.queries;
                if (queries && queries.length > 0) {
                    const pi = queries[0].state?.data?.browse?.results?.pageInfo;
                    if (pi) {
                        pagination.currentPage = pi.page;
                        pagination.totalPages = pi.pageCount;
                        pagination.totalResults = pi.total;
                        pagination.resultsPerPage = pi.limit;
                    }
                }
            } catch (e) {}
        }
        const nextHref = $("#pagination-control a[aria-label='Next']").attr("href");
        if (nextHref) pagination.nextPageUrl = makeAbsoluteURL(nextHref);
        outputData.pagination = pagination;

        const products = [];
        $("div[data-testid='productTile']").each((i, el) => {
            const $tile = $(el);
            const p = {
                availability: "in_stock",
                name: $tile.find("[data-testid='product-tile-title']").text().trim(),
                isPrime: false,
                isSponsored: $tile.find("[data-testid='sponsored-tag']").length > 0,
                preDiscountPrice: null,
                rating: null,
                reviewCount: null
            };

            const nameParts = p.name.split(" ");
            p.brand = nameParts.length > 0 ? nameParts[0] : "";

            const priceText = $tile.find("[data-testid='product-tile-lowest-ask-amount']").text();
            p.currency = detectCurrency(priceText);
            p.image = $tile.find("img").attr("src") || "";

            const cleanPriceMatch = priceText.match(/[\d,]+/);
            if (cleanPriceMatch) {
                p.price = parseFloat(cleanPriceMatch[0].replace(/,/g, ""));
            } else {
                p.price = 0.0;
            }

            let link = $tile.closest("a").attr("href") || $tile.find("a").first().attr("href") || "";
            p.url = makeAbsoluteURL(link);

            let productId = $tile.attr("data-id") || "";
            let urlSlug = "";
            if (link) {
                const parts = link.split('?')[0].split('/').filter(Boolean);
                if (parts.length > 0) urlSlug = parts[parts.length - 1];
            }

            if (!productId && nextData && urlSlug) {
                try {
                    const queries = nextData.props?.pageProps?.states?.query?.value?.queries || [];
                    for (const q of queries) {
                        const edges = q.state?.data?.browse?.results?.edges || [];
                        const foundNode = edges.find(e => e.node?.urlKey === urlSlug);
                        if (foundNode && foundNode.node.id) {
                            productId = foundNode.node.id;
                            break;
                        }
                    }
                } catch (e) {}
            }

            p.productId = productId || urlSlug || "";
            products.push(p);
        });
        outputData.products = products;

        const subcategories = [];
        $(".FilterAccordionContainer .filter a").each((i, el) => {
            const $el = $(el);
            const subName = $el.text().trim();
            const subUrl = $el.attr("href");
            if (subName) {
                subcategories.push({
                    name: subName,
                    productCount: null,
                    url: makeAbsoluteURL(subUrl)
                });
            }
        });
        outputData.subcategories = subcategories;

        return outputData;
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Puppeteer with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Puppeteer browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let page = null;
        
        try {
            page = await browser.newPage();
            
            await page.setViewport({ width: 1920, height: 1080 });
            
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36');
            
            await page.setRequestInterception(true);
            page.on('request', (request) => {
                const resourceType = request.resourceType();
                if (['image', 'media', 'font', 'stylesheet'].includes(resourceType)) {
                    request.abort();
                } else {
                    request.continue();
                }
            });
            
            await page.authenticate({
                username: PROXY_USERNAME,
                password: PROXY_PASSWORD
            });
            
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            // Wait for product tiles to appear
            try {
                await page.waitForSelector("div[data-testid='productTile']", { timeout: 10000 });
            } catch (e) {
                console.warn('Selector data-testid="productTile" not found within timeout');
            }
            
            const bodyHTML = await page.evaluate(() => document.body.innerHTML);
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    const browser = await puppeteer.launch({
        headless: 'new',
        ignoreHTTPSErrors: true,
        args: [
            `--proxy-server=http://${PROXY_SERVER}:${PROXY_PORT}`,
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://stockx.com/category/electronics',
    ];

    console.log('Starting concurrent scraping with NodeJS Puppeteer-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };