/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const { chromium } = require('playwright-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
chromium.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'stockx_com_product_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_CONFIG = {
    server: 'http://residential-proxy.scrapeops.io:8181',
    username: 'scrapeops',
    password: API_KEY
};

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Utility to strip HTML tags from a string
 * @param {string} html 
 * @returns {string}
 */
function stripHTML(html) {
    if (!html) return '';
    return html.replace(/<[^>]*>/g, ' ').trim();
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            const domain = "https://stockx.com";
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            const text = priceText.toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        const extractNumericPrice = (priceText) => {
            if (!priceText) return 0;
            const cleanText = priceText.replace(/,/g, '');
            const match = cleanText.match(/([\d,]+\.?\d*)/);
            if (match && match[1]) {
                return parseFloat(match[1]);
            }
            return 0;
        };

        // JSON-LD Extraction
        let jsonLD = null;
        $("script[type='application/ld+json']").each((i, el) => {
            try {
                const data = JSON.parse($(el).html());
                if (data["@type"] === "Product") {
                    jsonLD = data;
                }
            } catch (e) {}
        });

        // NEXT_DATA Extraction
        let nextData = null;
        try {
            const nextDataHtml = $("script#__NEXT_DATA__").html();
            if (nextDataHtml) {
                nextData = JSON.parse(nextDataHtml);
            }
        } catch (e) {}

        const outputData = {};
        outputData["timestamp"] = new Date().toISOString();

        // Aggregate Rating
        outputData["aggregateRating"] = jsonLD?.aggregateRating || null;

        // Availability
        let availability = "in_stock";
        const jsonLdAvail = jsonLD?.offers?.availability || "";
        if (jsonLdAvail.includes("InStock")) {
            availability = "in_stock";
        } else if (jsonLdAvail.includes("OutOfStock")) {
            availability = "out_of_stock";
        }
        outputData["availability"] = availability;

        // Brand
        let brand = jsonLD?.brand?.name || "";
        if (!brand) {
            brand = $("[data-testid='breadcrumb-schema']").text().trim();
            if (!brand) {
                brand = $(".chakra-breadcrumb__list-item").last().text().trim();
            }
        }
        outputData["brand"] = brand;

        // Category
        let category = jsonLD?.category || "";
        if (!category) {
            $(".chakra-breadcrumb__link").each((i, el) => {
                const txt = $(el).text().trim().toLowerCase();
                if (txt !== "home" && txt !== brand.toLowerCase()) {
                    category = txt;
                    return false; // break
                }
            });
        }
        outputData["category"] = category;

        // Price and Currency
        // Target active/main trade box price
        const priceText = $("[data-testid='trade-box-buy-amount']").first().text().trim();
        outputData["currency"] = priceText ? detectCurrency(priceText) : (jsonLD?.offers?.priceCurrency || "USD");
        outputData["price"] = priceText ? extractNumericPrice(priceText) : (jsonLD?.offers?.lowPrice || extractNumericPrice(jsonLD?.offers?.price || ""));

        // Description
        outputData["description"] = jsonLD?.description || $("[data-component='ProductDescription'] p").first().text().trim();

        // Features
        outputData["features"] = [];

        // Image Gallery Processing
        let galleryURLs = [];
        const productName = jsonLD?.name || $("h1[data-component='primary-product-title']").first().text().trim();

        if (nextData) {
            const queries = nextData?.props?.pageProps?.states?.query?.value?.queries || nextData?.props?.pageProps?.states?.query?.queries || [];
            for (const q of queries) {
                const gallery = q?.state?.data?.product?.media?.gallery;
                if (Array.isArray(gallery)) {
                    gallery.forEach(u => {
                        if (typeof u === 'string' && !u.includes("Surfacing_Reviews") && !u.includes("merchandising") && !u.includes("assets/blt")) {
                            galleryURLs.push(u);
                        }
                    });
                }
            }
        }

        if (galleryURLs.length === 0) {
            $("div[data-testid='MultiImage'] .chakra-tabs__tablist img").each((i, el) => {
                const src = $(el).attr("src");
                if (src && !src.includes("data:image") && !src.includes("assets/blt") && !src.includes("Surfacing_Reviews")) {
                    galleryURLs.push(src);
                }
            });
        }

        const images = [];
        const seen = new Set();
        for (const imgURL of galleryURLs) {
            let finalURL = imgURL
                .replace(/w=\d+/, "w=1200")
                .replace(/h=\d+/, "h=857")
                .replace(/q=\d+/, "q=90")
                .replace(/&dpr=[^&]*/g, "")
                .replace(/&fm=[^&]*/g, "")
                .replace(/&auto=[^&]*/g, "")
                .replace(/\?&/, "?")
                .replace(/&&+/g, "&")
                .replace(/&$/, "");

            if (seen.has(finalURL)) continue;
            seen.add(finalURL);

            images.push({
                url: makeAbsoluteURL(finalURL),
                alt_text: imgURL.includes("-2.jpg") ? `${productName} back view` : productName
            });
        }
        outputData["images"] = images;
        outputData["name"] = productName;
        outputData["preDiscountPrice"] = null;

        // Product ID
        let productId = jsonLD?.sku || "";
        if (!productId && nextData) {
            const queries = nextData?.props?.pageProps?.states?.query?.queries || [];
            if (queries.length > 0) {
                productId = queries[0]?.state?.data?.product?.id || "";
            }
        }
        outputData["productId"] = productId;
        outputData["reviews"] = [];

        // Seller
        const seller = { name: "StockX", rating: null, url: "https://stockx.com" };
        const sName = $(".seller-name").first().text().trim();
        if (sName) seller.name = sName;
        outputData["seller"] = seller;

        // Serial Numbers / Traits
        const serialNumbers = [];
        if (productId) serialNumbers.push({ type: "SKU", value: productId });
        if (jsonLD?.gtin) serialNumbers.push({ type: "GTIN", value: jsonLD.gtin });
        
        const specifications = [];
        $("[data-component='ProductTraits'] div").each((i, el) => {
            const key = $(el).find("span").text().trim();
            const val = $(el).find("p").text().trim();
            if (key && val) {
                specifications.push({ key, value: val });
                if (key.toLowerCase().includes("style")) {
                    serialNumbers.push({ type: "Other", value: val });
                }
            }
        });
        outputData["serialNumbers"] = serialNumbers;
        outputData["specifications"] = specifications;

        // Canonical URL
        let finalUrl = jsonLD?.url || $("link[rel='canonical']").attr("href") || url;
        outputData["url"] = makeAbsoluteURL(finalUrl);
        outputData["videos"] = [];

        return outputData;
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Playwright with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Playwright browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let context = null;
        let page = null;
        
        try {
            context = await browser.newContext({
                ignoreHTTPSErrors: true,
                viewport: { width: 1920, height: 1080 },
                userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
            });
            
            page = await context.newPage();
            
            // Block images/styles for speed initially, but we need them for some extraction logic 
            // The Go code relies on HTML/JSON structure mostly, so let's stick to blocking for performance
            await page.route('**/*', (route) => {
                const resourceType = route.request().resourceType();
                if (['image', 'media', 'font'].includes(resourceType)) {
                    route.abort();
                } else {
                    route.continue();
                }
            });
            
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            // Wait for dynamic component to ensure NEXT_DATA or attributes are ready
            await page.waitForTimeout(2000);
            
            const bodyHTML = await page.content();
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            if (context) await context.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    const browser = await chromium.launch({
        headless: true,
        proxy: PROXY_CONFIG,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://stockx.com/adidas-ctt-chinese-track-top-31-gender-neutral-jacket-asia-sizing-dark-grey',
    ];

    console.log('Starting concurrent scraping with NodeJS Playwright-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

// Run the scraper if this file is executed directly
if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };