/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const { chromium } = require('playwright-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
chromium.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'stockx_com_product_category_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_CONFIG = {
    server: 'http://residential-proxy.scrapeops.io:8181',
    username: 'scrapeops',
    password: API_KEY
};

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            const domain = "https://stockx.com";
            return urlStr.startsWith("/") ? domain + urlStr : domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            const text = (priceText || "").toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        const cleanPrice = (priceText) => {
            const match = (priceText || "").match(/[\d,]+\.?\d*/);
            if (match) {
                const val = match[0].replace(/,/g, "");
                return parseFloat(val) || 0;
            }
            return 0;
        };

        let nextData = null;
        const nextDataScript = $("script#__NEXT_DATA__").text();
        if (nextDataScript) {
            try {
                nextData = JSON.parse(nextDataScript);
            } catch (e) {}
        }

        const outputData = {};
        let appliedFilters = [];

        if (nextData) {
            try {
                const advFilters = nextData?.props?.pageProps?.states?.query?.value?.queries?.[0]?.state?.data?.browse?.filtersConfig?.advanced || [];
                for (const f of advFilters) {
                    if (f.selected) {
                        appliedFilters.push({
                            filterName: f.name,
                            filterValue: f.options?.[0]?.name || ""
                        });
                    }
                }
            } catch (e) {}
        }

        if (appliedFilters.length === 0) {
            const catVal = $("p.chakra-text.css-m41fx8").first().text().trim();
            if (catVal) {
                appliedFilters.push({
                    filterName: "CATEGORY",
                    filterValue: catVal
                });
            }
        }
        outputData.appliedFilters = appliedFilters;

        const banner = $("meta[property='og:image']").attr("content") || "";
        outputData.bannerImage = makeAbsoluteURL(banner);

        const breadcrumbs = [];
        $("li.chakra-breadcrumb__list-item").each((i, el) => {
            const s = $(el);
            const link = s.find("a");
            breadcrumbs.push({
                name: s.text().trim(),
                url: link.length > 0 ? makeAbsoluteURL(link.attr("href") || "") : ""
            });
        });
        outputData.breadcrumbs = breadcrumbs;
        outputData.categoryId = "electronics";

        let categoryName = "";
        const h1 = $("h1.chakra-heading, h1#electronics, [data-testid='Header'] h1").first();
        if (h1.length > 0) categoryName = h1.text().trim();

        if (!categoryName) {
            const lastBC = $("li.chakra-breadcrumb__list-item").last();
            if (lastBC.length > 0) {
                let val = lastBC.find(".chakra-breadcrumb__link").text() || lastBC.text();
                categoryName = val.replace(/\//g, "").trim();
            }
        }

        if (!categoryName) {
            const schemaText = $("script[data-testid='breadcrumb-schema']").text();
            if (schemaText) {
                try {
                    const data = JSON.parse(schemaText);
                    const items = data.itemListElement || [];
                    if (items.length > 0) {
                        categoryName = items[items.length - 1]?.item?.name || "";
                    }
                } catch (e) {}
            }
        }

        if (!categoryName) {
            const activeFilter = $("[data-testid='TreeFilter'] .filter > p").first();
            if (activeFilter.length > 0) categoryName = activeFilter.text().trim();
        }

        if (!categoryName) {
            const title = $("title").text();
            if (title.includes("Buy and Sell ")) {
                categoryName = title.replace("Buy and Sell ", "").split(" -")[0].trim();
            } else if (title.includes("StockX")) {
                categoryName = title.split(" -")[0].trim();
            }
        }
        outputData.categoryName = categoryName;
        outputData.categoryUrl = makeAbsoluteURL($("link[rel='canonical']").attr("href") || "/category/electronics");
        outputData.description = $("p.chakra-text.css-1o63kog").first().text().trim();

        outputData.pagination = {
            currentPage: 1,
            nextPageUrl: makeAbsoluteURL($("a[aria-label='Next']").attr("href") || ""),
            prevPageUrl: null,
            resultsPerPage: 40,
            totalPages: 25,
            totalResults: 1000
        };

        const productIDMap = {};
        const productNameMap = {};
        const productBrandMap = {};

        if (nextData) {
            const findProducts = (val) => {
                if (!val || typeof val !== 'object') return;
                if (Array.isArray(val)) {
                    val.forEach(findProducts);
                    return;
                }
                
                let id = val.objectId || val.id;
                let urlKey = val.urlKey;
                let title = val.title;
                let brand = val.brand;

                if (val.node) {
                    urlKey = urlKey || val.node.urlKey;
                    title = title || val.node.title;
                    brand = brand || val.node.brand;
                    id = id || val.node.id || val.node.objectId;
                }

                if (id) {
                    if (urlKey) {
                        productIDMap[urlKey] = id;
                        if (brand) productBrandMap[urlKey] = brand;
                    }
                    if (title) {
                        productNameMap[title.trim().toLowerCase()] = id;
                    }
                }
                Object.values(val).forEach(findProducts);
            };
            findProducts(nextData);
        }

        const products = [];
        $("div[data-testid='productTile'], div[data-testid='VariantTile']").each((i, el) => {
            const s = $(el);
            const name = s.find("[data-testid='product-tile-title']").text().trim();
            const priceText = s.find("[data-testid='product-tile-lowest-ask-amount']").text();
            const rawUrl = s.find("a").attr("href") || "";
            const urlPath = rawUrl.split("?")[0].replace(/^\/+|\/+$/g, "");
            const segments = urlPath.split("/");
            const slug = segments.length > 0 ? segments[segments.length - 1] : "";

            let brand = (slug && productBrandMap[slug]) || "";
            if (!brand) {
                const lowerName = name.toLowerCase();
                const brands = ["Canon", "Nintendo", "Apple", "Sony", "NVIDIA", "Microsoft", "Logitech", "Samsung", "Dell", "HP", "Asus", "Acer", "Lenovo"];
                brand = brands.find(b => lowerName.includes(b.toLowerCase())) || "";
            }
            if (!brand && name) brand = name.split(/\s+/)[0];

            let foundID = (slug && productIDMap[slug]) || productNameMap[name.toLowerCase()] || "";
            if (!foundID) {
                const uuidMatch = rawUrl.match(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/);
                if (uuidMatch) foundID = uuidMatch[0];
            }

            products.push({
                availability: "in_stock",
                brand,
                currency: detectCurrency(priceText),
                image: makeAbsoluteURL(s.find("img").attr("src") || ""),
                isPrime: false,
                isSponsored: s.find("[data-testid='sponsored-tag']").length > 0 || s.attr("data-sponsored-listing") === "true",
                name,
                preDiscountPrice: null,
                price: cleanPrice(priceText),
                url: makeAbsoluteURL(rawUrl),
                productId: foundID,
                rating: null,
                reviewCount: null
            });
        });
        outputData.products = products;

        const subcategories = [];
        $("div.filter.css-qlswoo a").each((i, el) => {
            const s = $(el);
            subcategories.push({
                name: s.text().trim(),
                productCount: 0,
                url: makeAbsoluteURL(s.attr("href") || "")
            });
        });
        outputData.subcategories = subcategories;

        return {
            ...outputData,
            url: url,
            timestamp: new Date().toISOString()
        };
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Playwright with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Playwright browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let context = null;
        let page = null;
        
        try {
            context = await browser.newContext({
                ignoreHTTPSErrors: true,
                viewport: { width: 1920, height: 1080 },
                userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
            });
            
            page = await context.newPage();
            
            await page.route('**/*', (route) => {
                const resourceType = route.request().resourceType();
                if (['image', 'media', 'font', 'stylesheet'].includes(resourceType)) {
                    route.abort();
                } else {
                    route.continue();
                }
            });
            
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            await page.waitForTimeout(2000); // Wait for dynamic hydration/NEXT_DATA
            
            const bodyHTML = await page.content();
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            if (context) await context.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    const browser = await chromium.launch({
        headless: true,
        proxy: PROXY_CONFIG,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://stockx.com/category/electronics',
    ];

    console.log('Starting concurrent scraping with NodeJS Playwright-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };